### ISSUE TITLE
使用 GitHub Actions 自动部署

### ISSUE THREAD

**Issue by liang2kl** [SAST-skill-docers/sast-skill-docs#27]
手动部署过于繁琐，是否可以考虑使用 GitHub Actions 对 `master` 分支自动进行部署

```yaml
name: deploy 
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
```
